version: "3.8"
services:
  agente-host:
    build: ./host
    network_mode: host
    restart: always
    ports:
      - "9000:9000"

  agente-rede:
    build: ./rede
    network_mode: host
    privileged: true  # necessário para acessar OVS
    restart: always
    ports:
      - "9001:9001"