FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y openvswitch-switch && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY main.py .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9001"]